/** Declaration file generated by dts-gen */

declare module 'bcryptjs' {
  export function compare(
    s: any,
    hash: any,
    callback?: any,
    progressCallback?: any
  ): any;

  export function compareSync(s: any, hash: any): any;

  export function decodeBase64(s: any, len: any): any;

  export function encodeBase64(b: any, len: any): any;

  export function genSalt(rounds: any, seed_length: any, callback: any): any;

  export function genSaltSync(rounds: any, seed_length: any): any;

  export function getRounds(hash: any): any;

  export function getSalt(hash: any): any;

  export function hash(
    s: any,
    salt: any,
    callback?: any,
    progressCallback?: any
  ): any;

  export function hashSync(s: any, salt: any): any;

  export function setRandomFallback(random: any): void;
}
