version: "1"
services:
    polyglotist_app:
        container_name: "polyglotist_app"
        build: /dist/
        ports:
            - "8080:8080"
    database:
        image: "postgres:12"
        container_name: "postgres"
        ports:
            - "5432:5432"