# Pull from a base image
FROM node:12-alpine

# Installs latest Chromium (77) package.
RUN apk add --no-cache \
    chromium \
    nss \
    freetype \
    freetype-dev \
    harfbuzz \
    ca-certificates \
    ttf-freefont \
    # nodejs \
    yarn

# Tell Puppeteer to skip installing Chrome. We'll be using the installed package.
ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true \
    PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium-browser

# Puppeteer v1.19.0 works with Chromium 77.
RUN yarn add puppeteer@1.19.0

# Comment out these lines and use --no-sandbox due to permissions with google cloud translation api and reading the api-key file.

# # Add user so we don't need --no-sandbox.
# RUN addgroup -S pptruser && adduser -S -g pptruser pptruser \
#     && mkdir -p /home/pptruser/Downloads /app \
#     && chown -R pptruser:pptruser /home/pptruser \
#     && chown -R pptruser:pptruser /app

# # Run everything after as non-privileged user.
# USER pptruser

# Copy the files from the current directory to app/
ADD . /app

# Use app/ as the working directory
WORKDIR /app

# Install dependencies (npm ci is similar to npm i, but for automated builds)
RUN npm i

# Listen on the specified port
EXPOSE 8080

EXPOSE 3000
# Set Node server
ENTRYPOINT npm run dev

