version: "3.8"
services:
    polyglotist_app:
        container_name: "app"
        build: .
        ports:
            - "8080:8080"
        links:
            - database #links database to app
            # - chrome #links to chrome instance
        volumes:
            - .:/dist
            - /dist/node_modules
        environment:
            DATABASE_URL: postgres://${DB_USER}:${DB_PASSWORD}@database:5432/api
            DB_HOST: database
        cap_add:
            - SYS_ADMIN
    database:
        image: "postgres:12" #just pull image from docker hub
        container_name: "postgres-12"
        restart: unless-stopped
        ports:
            - "5432:5432"
        environment:
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_USER: ${DB_USER}
            POSTGRES_DB: ${DB_DATABASE}
    # chrome:
    #     container_name: "chrome_browser"
    #     build: ./chrome_browser
    #     cap_add:
    #         - SYS_ADMIN
    #     shm_size: '1gb'
    #     ports:
    #         - "9222:9222"

# to execuse docker-compose, execute sudo docker-compose -f docker/docker-compose.yml up
# -f specifies the path to the docker-compose from root project folder where command should be executed        