version: "3.8"
services:
    polyglotist_app:
        container_name: "polyglotist_app"
        build: .
        ports:
            - "8080:8080"
        links:
            - database #links database to app
        volumes:
            - .:/dist
            - /dist/node_modules
        environment:
            DATABASE_URL: postgres://${DB_USER}:${DB_PASSWORD}@database:5432/api
            DB_HOST: database
    database:
        image: "postgres:12" #just pull image from docker hub
        container_name: "postgres-12"
        restart: unless-stopped
        ports:
            - "5432:5432"
        environment:
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_USER: ${DB_USER}
            POSTGRES_DB: ${DB_DATABASE}

# to execuse docker-compose, execute docker-compose up        